on:
  push:
    branches:
      - master

name: publish-site

jobs:
  publish-site:
    runs-on: ubuntu-latest
    container: dbarrows/spur-image
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: remotes::install_deps(dependencies = TRUE)
        shell: Rscript --vanilla {0}
      - name : Install package
        run: R --vanilla CMD INSTALL .
      - name: Set Git Identity
        run: |
            git config user.email "dexter@barrows.io"
            git config user.name "Dexter Barrows"
      - name: Publish
        run: pkgdown::deploy_to_branch(new_process = FALSE)
        shell: Rscript --vanilla {0}