on:
  push:
    paths:
      - README.Rmd

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
    
      - name: Install dependencies
        run: |
          install.packages(c('rmarkdown', 'svglite', 'showtext', 'devtools'))
          devtools::install_deps()
        shell: Rscript {0}
    
      - name: Render README
        run: rmarkdown::render('README.Rmd')
        shell: Rscript {0}
    
      - name: Commit results
        run: |
          git commit README.md man/figures -m 'Re-build README.Rmd' || echo 'No changes to commit'
          git push origin || echo 'No changes to commit'